version: "3.8"

services:
  server:
    image: bogem/ftp
    env_file:
      - .env
    ports:
      - '20:20'
      - '21:21'
      - '47400-47470:47400-47470'
    volumes:
      - 'D:\Documentos\File-Server:/home/vsftpd'
